[tool.poetry]
name = "originheal"
version = "0.1.0"
description = ""
license = "=MIT"
authors = ["zfq <you@example.com>"]
readme = "README.md"

[tool.black]
line-length = 128
previcw = true
unstable = true
target-version = ["py311"]


[tool.poetry.dependencies]
python = "^3.11"
black = "^24.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
